#!/bin/bash

# echo bash

echo c
cc c/loops.c -O3 -o c/loops.out > /dev/null

echo crystal
crystal build crystal/loops.cr -o crystal/loops > /dev/null

echo csharp
dotnet build csharp > /dev/null

echo fsharp
dotnet build fsharp > /dev/null

echo haskell
ghc haskell/loops.hs -o haskell/loops > /dev/null

echo java
javac -d java java/Loops.java > /dev/null

# echo javascript
# echo julia
# echo powershell
# echo python
# echo python3
# echo ruby

echo typescript
tsc typescript/loops.ts --out typescript/loops.js --target esnext > /dev/null
