' Gambas module file
Library "libc:6"

Public Struct Timeval
  tv_sec As Long
  tv_usec As Long
End Struct

Extern gettimeofday(tv As Timeval, tz As Pointer) As Integer In "libc:6"

Public Sub Main()
  Dim tStart As New Timeval
  Dim tEnd As New Timeval
  Dim fDiff As Float
  gettimeofday(tStart, Null)

  Dim iterations As Integer = Val(Args[1])
  Dim sampleSize As Integer = 23
  Dim count As Integer = 0

  Dim r As Integer
  For r = 1 To iterations
    Dim sample As New Integer[365]
    Dim c As Integer
    For c = 1 To sampleSize
      Dim num As Integer = Rand(0, 364)
      If sample[num] = 1 Then
        Inc count
        Break
      Else
        sample[num] = 1
      Endif
    Next
  Next

  Print "iterations: " & iterations
  Print "sample-size: " & sampleSize
  Dim percent As Float = count / iterations * 100
  Print "percent: " & Format(percent, ".00")
  gettimeofday(tEnd, Null)
  fDiff = (tEnd.tv_sec - tStart.tv_sec) + ((tEnd.tv_usec - tStart.tv_usec) / 1000000.0)
  Print "seconds: " & Format$(fDiff, "0.000000")
End
