FROM debian:stable-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    gfortran && \
    rm -rf /var/lib/apt/lists/*


COPY hello.f90 .
RUN gfortran hello.f90 -o hello

ENTRYPOINT ["./hello"]
