FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache cargo git libgcc && \
    cargo install --git https://github.com/redox-os/ion/ ion-shell && \
    apk del cargo git

ENV PATH="/root/.cargo/bin:${PATH}"


COPY loops.ion .

ENTRYPOINT ["ion", "loops.ion"]
